### ISSUE TITLE
Why the stream is always limit to 1? How does it allow multiple readers?

### ISSUE THREAD

**Issue by the-bytecode** [virendrac/Java-Learning-Virendra#24]
https://github.com/virendrac/Java-Learning-Virendra/blob/9940e7cb003f191ea9136405085bfa584f7a4b23/WikiCall/src/main/java/com/learning/pramati/wiki/fileloader/FileLoader.java#L32

**Comment by virendrac** [comment]
here I'm only reading the first line to determine the format of the file.
